#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using CapaDominio;

namespace CapaDominio	
{
	public partial class Direccion
	{
		private int idDireccion;
		public virtual int IdDireccion
		{
			get
			{
				return this.idDireccion;
			}
			set
			{
				this.idDireccion = value;
			}
		}
		
		private string calle;
		public virtual string Calle
		{
			get
			{
				return this.calle;
			}
			set
			{
				this.calle = value;
			}
		}
		
		private int? numero;
		public virtual int? Numero
		{
			get
			{
				return this.numero;
			}
			set
			{
				this.numero = value;
			}
		}
		
		private int? piso;
		public virtual int? Piso
		{
			get
			{
				return this.piso;
			}
			set
			{
				this.piso = value;
			}
		}
		
		private string departamento;
		public virtual string Departamento
		{
			get
			{
				return this.departamento;
			}
			set
			{
				this.departamento = value;
			}
		}
		
		private int? localidad;
		public virtual int? Localidad
		{
			get
			{
				return this.localidad;
			}
			set
			{
				this.localidad = value;
			}
		}
		
		private Localidad localidad1;
		public virtual Localidad Localidad1
		{
			get
			{
				return this.localidad1;
			}
			set
			{
				this.localidad1 = value;
			}
		}
		
		private IList<Inmueble> inmuebles = new List<Inmueble>();
		public virtual IList<Inmueble> Inmuebles
		{
			get
			{
				return this.inmuebles;
			}
		}
		
	}
}
#pragma warning restore 1591
