#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ContextGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using CapaDominio;

namespace CapaDominio	
{
	public partial class ModeloDeDominio : OpenAccessContext, IModeloDeDominioUnitOfWork
	{
		private static string connectionStringName = @"InmodbConnection";
			
		private static BackendConfiguration backend = GetBackendConfiguration();
				
		private static MetadataSource metadataSource = XmlMetadataSource.FromAssemblyResource("EntitiesModel.rlinq");
		
		public ModeloDeDominio()
			:base(connectionStringName, backend, metadataSource)
		{ }
		
		public ModeloDeDominio(string connection)
			:base(connection, backend, metadataSource)
		{ }
		
		public ModeloDeDominio(BackendConfiguration backendConfiguration)
			:base(connectionStringName, backendConfiguration, metadataSource)
		{ }
			
		public ModeloDeDominio(string connection, MetadataSource metadataSource)
			:base(connection, backend, metadataSource)
		{ }
		
		public ModeloDeDominio(string connection, BackendConfiguration backendConfiguration, MetadataSource metadataSource)
			:base(connection, backendConfiguration, metadataSource)
		{ }
			
		public IQueryable<Usuario> Usuarios 
		{
			get
			{
				return this.GetAll<Usuario>();
			}
		}
		
		public IQueryable<TipoOperacion> TipoOperacions 
		{
			get
			{
				return this.GetAll<TipoOperacion>();
			}
		}
		
		public IQueryable<TipoInmueble> TipoInmuebles 
		{
			get
			{
				return this.GetAll<TipoInmueble>();
			}
		}
		
		public IQueryable<TipoEstado> TipoEstados 
		{
			get
			{
				return this.GetAll<TipoEstado>();
			}
		}
		
		public IQueryable<TipoCaracteristica> TipoCaracteristicas 
		{
			get
			{
				return this.GetAll<TipoCaracteristica>();
			}
		}
		
		public IQueryable<TipoAmbiente> TipoAmbientes 
		{
			get
			{
				return this.GetAll<TipoAmbiente>();
			}
		}
		
		public IQueryable<Rol_Permiso> Rol_Permisos 
		{
			get
			{
				return this.GetAll<Rol_Permiso>();
			}
		}
		
		public IQueryable<Rol> Rols 
		{
			get
			{
				return this.GetAll<Rol>();
			}
		}
		
		public IQueryable<Provincium> Provincia 
		{
			get
			{
				return this.GetAll<Provincium>();
			}
		}
		
		public IQueryable<Permiso> Permisos 
		{
			get
			{
				return this.GetAll<Permiso>();
			}
		}
		
		public IQueryable<Moneda> Monedas 
		{
			get
			{
				return this.GetAll<Moneda>();
			}
		}
		
		public IQueryable<Localidad> Localidads 
		{
			get
			{
				return this.GetAll<Localidad>();
			}
		}
		
		public IQueryable<Inmueble_TipoOperacion> Inmueble_TipoOperacions 
		{
			get
			{
				return this.GetAll<Inmueble_TipoOperacion>();
			}
		}
		
		public IQueryable<Inmueble_Caracteristica> Inmueble_Caracteristicas 
		{
			get
			{
				return this.GetAll<Inmueble_Caracteristica>();
			}
		}
		
		public IQueryable<Inmueble_Ambiente> Inmueble_Ambientes 
		{
			get
			{
				return this.GetAll<Inmueble_Ambiente>();
			}
		}
		
		public IQueryable<Inmueble> Inmuebles 
		{
			get
			{
				return this.GetAll<Inmueble>();
			}
		}
		
		public IQueryable<Imagen> Imagens 
		{
			get
			{
				return this.GetAll<Imagen>();
			}
		}
		
		public IQueryable<Direccion> Direccions 
		{
			get
			{
				return this.GetAll<Direccion>();
			}
		}
		
		public static BackendConfiguration GetBackendConfiguration()
		{
			BackendConfiguration backend = new BackendConfiguration();
			backend.Backend = "MsSql";
			backend.ProviderName = "System.Data.SqlClient";
		
			CustomizeBackendConfiguration(ref backend);
		
			return backend;
		}
		
		/// <summary>
		/// Allows you to customize the BackendConfiguration of ModeloDeDominio.
		/// </summary>
		/// <param name="config">The BackendConfiguration of ModeloDeDominio.</param>
		static partial void CustomizeBackendConfiguration(ref BackendConfiguration config);
		
	}
	
	public interface IModeloDeDominioUnitOfWork : IUnitOfWork
	{
		IQueryable<Usuario> Usuarios
		{
			get;
		}
		IQueryable<TipoOperacion> TipoOperacions
		{
			get;
		}
		IQueryable<TipoInmueble> TipoInmuebles
		{
			get;
		}
		IQueryable<TipoEstado> TipoEstados
		{
			get;
		}
		IQueryable<TipoCaracteristica> TipoCaracteristicas
		{
			get;
		}
		IQueryable<TipoAmbiente> TipoAmbientes
		{
			get;
		}
		IQueryable<Rol_Permiso> Rol_Permisos
		{
			get;
		}
		IQueryable<Rol> Rols
		{
			get;
		}
		IQueryable<Provincium> Provincia
		{
			get;
		}
		IQueryable<Permiso> Permisos
		{
			get;
		}
		IQueryable<Moneda> Monedas
		{
			get;
		}
		IQueryable<Localidad> Localidads
		{
			get;
		}
		IQueryable<Inmueble_TipoOperacion> Inmueble_TipoOperacions
		{
			get;
		}
		IQueryable<Inmueble_Caracteristica> Inmueble_Caracteristicas
		{
			get;
		}
		IQueryable<Inmueble_Ambiente> Inmueble_Ambientes
		{
			get;
		}
		IQueryable<Inmueble> Inmuebles
		{
			get;
		}
		IQueryable<Imagen> Imagens
		{
			get;
		}
		IQueryable<Direccion> Direccions
		{
			get;
		}
	}
}
#pragma warning restore 1591
