#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using CapaDominio;

namespace CapaDominio	
{
	public partial class Inmueble_Ambiente
	{
		private int idInmueble_Ambiente;
		public virtual int IdInmueble_Ambiente
		{
			get
			{
				return this.idInmueble_Ambiente;
			}
			set
			{
				this.idInmueble_Ambiente = value;
			}
		}
		
		private int? idInmueble;
		public virtual int? IdInmueble
		{
			get
			{
				return this.idInmueble;
			}
			set
			{
				this.idInmueble = value;
			}
		}
		
		private int? idTipoAmbiente;
		public virtual int? IdTipoAmbiente
		{
			get
			{
				return this.idTipoAmbiente;
			}
			set
			{
				this.idTipoAmbiente = value;
			}
		}
		
		private int? cantidad;
		public virtual int? Cantidad
		{
			get
			{
				return this.cantidad;
			}
			set
			{
				this.cantidad = value;
			}
		}
		
		private Inmueble inmueble;
		public virtual Inmueble Inmueble
		{
			get
			{
				return this.inmueble;
			}
			set
			{
				this.inmueble = value;
			}
		}
		
		private TipoAmbiente tipoAmbiente;
		public virtual TipoAmbiente TipoAmbiente
		{
			get
			{
				return this.tipoAmbiente;
			}
			set
			{
				this.tipoAmbiente = value;
			}
		}
		
	}
}
#pragma warning restore 1591
