#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using CapaDominio;

namespace CapaDominio	
{
	public partial class Inmueble
	{
		private int idInmueble;
		public virtual int IdInmueble
		{
			get
			{
				return this.idInmueble;
			}
			set
			{
				this.idInmueble = value;
			}
		}
		
		private int? direccion;
		public virtual int? Direccion
		{
			get
			{
				return this.direccion;
			}
			set
			{
				this.direccion = value;
			}
		}
		
		private int? tipoInmueble;
		public virtual int? TipoInmueble
		{
			get
			{
				return this.tipoInmueble;
			}
			set
			{
				this.tipoInmueble = value;
			}
		}
		
		private string titulo;
		public virtual string Titulo
		{
			get
			{
				return this.titulo;
			}
			set
			{
				this.titulo = value;
			}
		}
		
		private string descripcion;
		public virtual string Descripcion
		{
			get
			{
				return this.descripcion;
			}
			set
			{
				this.descripcion = value;
			}
		}
		
		private decimal? valor;
		public virtual decimal? Valor
		{
			get
			{
				return this.valor;
			}
			set
			{
				this.valor = value;
			}
		}
		
		private int? moneda;
		public virtual int? Moneda
		{
			get
			{
				return this.moneda;
			}
			set
			{
				this.moneda = value;
			}
		}
		
		private bool? isDestacada;
		public virtual bool? IsDestacada
		{
			get
			{
				return this.isDestacada;
			}
			set
			{
				this.isDestacada = value;
			}
		}
		
		private DateTime? fechaPublicacion;
		public virtual DateTime? FechaPublicacion
		{
			get
			{
				return this.fechaPublicacion;
			}
			set
			{
				this.fechaPublicacion = value;
			}
		}
		
		private int? tipoEstado;
		public virtual int? TipoEstado
		{
			get
			{
				return this.tipoEstado;
			}
			set
			{
				this.tipoEstado = value;
			}
		}
		
		private int? usuario;
		public virtual int? Usuario
		{
			get
			{
				return this.usuario;
			}
			set
			{
				this.usuario = value;
			}
		}
		
		private Direccion direccion1;
		public virtual Direccion Direccion1
		{
			get
			{
				return this.direccion1;
			}
			set
			{
				this.direccion1 = value;
			}
		}
		
		private Moneda moneda1;
		public virtual Moneda Moneda1
		{
			get
			{
				return this.moneda1;
			}
			set
			{
				this.moneda1 = value;
			}
		}
		
		private TipoEstado tipoEstado1;
		public virtual TipoEstado TipoEstado1
		{
			get
			{
				return this.tipoEstado1;
			}
			set
			{
				this.tipoEstado1 = value;
			}
		}
		
		private TipoInmueble tipoInmueble1;
		public virtual TipoInmueble TipoInmueble1
		{
			get
			{
				return this.tipoInmueble1;
			}
			set
			{
				this.tipoInmueble1 = value;
			}
		}
		
		private Usuario usuario1;
		public virtual Usuario Usuario1
		{
			get
			{
				return this.usuario1;
			}
			set
			{
				this.usuario1 = value;
			}
		}
		
		private IList<Inmueble_TipoOperacion> inmueble_TipoOperacions = new List<Inmueble_TipoOperacion>();
		public virtual IList<Inmueble_TipoOperacion> Inmueble_TipoOperacions
		{
			get
			{
				return this.inmueble_TipoOperacions;
			}
		}
		
		private IList<Inmueble_Caracteristica> inmueble_Caracteristicas = new List<Inmueble_Caracteristica>();
		public virtual IList<Inmueble_Caracteristica> Inmueble_Caracteristicas
		{
			get
			{
				return this.inmueble_Caracteristicas;
			}
		}
		
		private IList<Inmueble_Ambiente> inmueble_Ambientes = new List<Inmueble_Ambiente>();
		public virtual IList<Inmueble_Ambiente> Inmueble_Ambientes
		{
			get
			{
				return this.inmueble_Ambientes;
			}
		}
		
		private IList<Imagen> imagens = new List<Imagen>();
		public virtual IList<Imagen> Imagens
		{
			get
			{
				return this.imagens;
			}
		}
		
	}
}
#pragma warning restore 1591
