#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using CapaDominio;

namespace CapaDominio	
{
	public partial class Inmueble_TipoOperacion
	{
		private int idInmueble_TipoOperacion;
		public virtual int IdInmueble_TipoOperacion
		{
			get
			{
				return this.idInmueble_TipoOperacion;
			}
			set
			{
				this.idInmueble_TipoOperacion = value;
			}
		}
		
		private int? idInmueble;
		public virtual int? IdInmueble
		{
			get
			{
				return this.idInmueble;
			}
			set
			{
				this.idInmueble = value;
			}
		}
		
		private int? idTipoOperacion;
		public virtual int? IdTipoOperacion
		{
			get
			{
				return this.idTipoOperacion;
			}
			set
			{
				this.idTipoOperacion = value;
			}
		}
		
		private Inmueble inmueble;
		public virtual Inmueble Inmueble
		{
			get
			{
				return this.inmueble;
			}
			set
			{
				this.inmueble = value;
			}
		}
		
		private TipoOperacion tipoOperacion;
		public virtual TipoOperacion TipoOperacion
		{
			get
			{
				return this.tipoOperacion;
			}
			set
			{
				this.tipoOperacion = value;
			}
		}
		
	}
}
#pragma warning restore 1591
