#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using CapaDominio;

namespace CapaDominio	
{
	public partial class Localidad
	{
		private int idLocalidad;
		public virtual int IdLocalidad
		{
			get
			{
				return this.idLocalidad;
			}
			set
			{
				this.idLocalidad = value;
			}
		}
		
		private string nombreLocalidad;
		public virtual string NombreLocalidad
		{
			get
			{
				return this.nombreLocalidad;
			}
			set
			{
				this.nombreLocalidad = value;
			}
		}
		
		private string codigoPostal;
		public virtual string CodigoPostal
		{
			get
			{
				return this.codigoPostal;
			}
			set
			{
				this.codigoPostal = value;
			}
		}
		
		private int? provincia;
		public virtual int? Provincia
		{
			get
			{
				return this.provincia;
			}
			set
			{
				this.provincia = value;
			}
		}
		
		private Provincium provincium;
		public virtual Provincium Provincium
		{
			get
			{
				return this.provincium;
			}
			set
			{
				this.provincium = value;
			}
		}
		
		private IList<Direccion> direccions = new List<Direccion>();
		public virtual IList<Direccion> Direccions
		{
			get
			{
				return this.direccions;
			}
		}
		
	}
}
#pragma warning restore 1591
