#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using CapaDominio;

namespace CapaDominio	
{
	public partial class Permiso
	{
		private int idPermiso;
		public virtual int IdPermiso
		{
			get
			{
				return this.idPermiso;
			}
			set
			{
				this.idPermiso = value;
			}
		}
		
		private byte[] nombrePermiso;
		public virtual byte[] NombrePermiso
		{
			get
			{
				return this.nombrePermiso;
			}
			set
			{
				this.nombrePermiso = value;
			}
		}
		
		private IList<Rol_Permiso> rol_Permisos = new List<Rol_Permiso>();
		public virtual IList<Rol_Permiso> Rol_Permisos
		{
			get
			{
				return this.rol_Permisos;
			}
		}
		
	}
}
#pragma warning restore 1591
