#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using CapaDominio;

namespace CapaDominio	
{
	public partial class Provincium
	{
		private int idProvincia;
		public virtual int IdProvincia
		{
			get
			{
				return this.idProvincia;
			}
			set
			{
				this.idProvincia = value;
			}
		}
		
		private string nombreProvincia;
		public virtual string NombreProvincia
		{
			get
			{
				return this.nombreProvincia;
			}
			set
			{
				this.nombreProvincia = value;
			}
		}
		
		private IList<Localidad> localidads = new List<Localidad>();
		public virtual IList<Localidad> Localidads
		{
			get
			{
				return this.localidads;
			}
		}
		
	}
}
#pragma warning restore 1591
