#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using CapaDominio;

namespace CapaDominio	
{
	public partial class TipoCaracteristica
	{
		private int idTipoCaracteristica;
		public virtual int IdTipoCaracteristica
		{
			get
			{
				return this.idTipoCaracteristica;
			}
			set
			{
				this.idTipoCaracteristica = value;
			}
		}
		
		private string nombre;
		public virtual string Nombre
		{
			get
			{
				return this.nombre;
			}
			set
			{
				this.nombre = value;
			}
		}
		
		private string unidadDeMedida;
		public virtual string UnidadDeMedida
		{
			get
			{
				return this.unidadDeMedida;
			}
			set
			{
				this.unidadDeMedida = value;
			}
		}
		
		private IList<Inmueble_Caracteristica> inmueble_Caracteristicas = new List<Inmueble_Caracteristica>();
		public virtual IList<Inmueble_Caracteristica> Inmueble_Caracteristicas
		{
			get
			{
				return this.inmueble_Caracteristicas;
			}
		}
		
	}
}
#pragma warning restore 1591
