#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using CapaDominio;

namespace CapaDominio	
{
	public partial class TipoAmbiente
	{
		private int idTipoAmbiente;
		public virtual int IdTipoAmbiente
		{
			get
			{
				return this.idTipoAmbiente;
			}
			set
			{
				this.idTipoAmbiente = value;
			}
		}
		
		private string nombre;
		public virtual string Nombre
		{
			get
			{
				return this.nombre;
			}
			set
			{
				this.nombre = value;
			}
		}
		
		private IList<Inmueble_Ambiente> inmueble_Ambientes = new List<Inmueble_Ambiente>();
		public virtual IList<Inmueble_Ambiente> Inmueble_Ambientes
		{
			get
			{
				return this.inmueble_Ambientes;
			}
		}
		
	}
}
#pragma warning restore 1591
